spring:
  application.name: demo
  jpa.hibernate.ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver


app:
  encryptor:
    password: "1234567890abcdef1234567890abcdef"
    salt: "1234567890abcdef"