spring:
  application.name: demo
  jpa.hibernate.ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver


app:
  encryptor:
    password: 'THE-password'
    salt: 'THE-salt'