spring:
  application.name: demo
  jpa.hibernate.ddl-auto: update
  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: postgres
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method

app:
  admin:
    username: "admin"
    password: "admin"
  encryptor:
    password: "1234567890abcdef1234567890abcdef"
    salt: "1234567890abcdef"
  secret-key: "1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef"
  token-expiration: 300000