spring:
  application.name: demo
#  jpa.hibernate.ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/migration/db.changelog-master.yaml

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
  docfile-path: docs/openapi.yaml

app:
  admin:
    username: "admin"
    password: "admin"
  encryptor:
    password: "1234567890abcdef1234567890abcdef"
    salt: "1234567890abcdef"
  secret-key: "1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef"
  token-expiration: 300000