spring:
  application:
    name: demo

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}

  config:
    import: optional:file:./config/application-secrets.yml

---
# Конфигурация для Docker
spring:
  profiles: docker

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  web:
    resources:
      cache:
        period: 0

---
# Конфигурация по умолчанию (development)
spring:
  profiles: default

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

---
# Общие настройки (для всех профилей)
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method

logging:
  level:
    com.yourpackage: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  file:
    name: /app/logs/application.log

app:
  admin:
    username: "admin"
    password: "admin"
  encryptor:
    password: "1234567890abcdef1234567890abcdef"
    salt: "1234567890abcdef"
  secret-key: "1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef"
  token-expiration: 300000